### ISSUE TITLE
Installation troubles

### ISSUE THREAD

**Issue by mauriziodidomenico** [stinnux/kanboard-bigboard#1]
Hi,

i installed your plugin in the dedicated folder and renamed it (BigBoard). Your plug in appears in the plugin list, but i can't recognize any additional feature.

![screenshot 2016-08-14 at 21](https://cloud.githubusercontent.com/assets/16655789/17651269/b44d718e-6263-11e6-99d1-1ff9d0e2794e.png)

Application version: master
PHP version: 7.0.7
PHP SAPI: apache2handler
OS version: Linux 4.4.11-1-ARCH
Database driver: sqlite
Database version: 3.13.0
Browser: Mozilla/5.0 (X11; CrOS x86_64 8350.68.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by stinnux** [comment]
The Bigboard needs some changes to the base kanboard (see PR #2474), which have not yet been applied. 

That is also the reason why there is not yet a release of BigBoard available
