### ISSUE TITLE
well actually not an issue but a big plus

### ISSUE THREAD

**Issue by neiaberau** [stinnux/kanboard-bigboard#10]
I do not know what you changed, but when installing bigbard, even when using on a single board, 
     https://github.com/kanboard/kanboard/issues/3625
seems not to be happining anymore. At least I cannot reproduce it anymore on a small test installation. 
Now I just have to test this with a productive version.

**Comment by neiaberau** [comment]
just wanted this to be known, so closing it already again

**Comment by stinnux** [comment]
I don‘t think that it’s related. As long as you aren‘t using the backboard you are running unchanged kamboard.

**Comment by neiaberau** [comment]
as soon as I install bigboard, it does not happen anymore.
I guessed it was due to changes in BoardDragAndDrop.js , ist this not overwritten?

**Comment by stinnux** [comment]
It only adds the boardid to the json query, that shouldn't change that much. 

Did you try to open the javascript console when the error occurs, probably that will give a hint on what the problem is.

**Comment by neiaberau** [comment]
with the kanboard issue I do not get an error, the tasks are just move to unexpected places, 
I do not know much about javascript or how to debug (I tried and did not understand anything)

when I compare the BoardDragAndDrop.js original and from bigboard, it seems to me, that the variable params is declared at another level:  in the kanboard version (outside dropzone.each(function()); in the bigboard version (inside dropzone.each(function()), but maybe I misunderstand javascript code.

**Comment by neiaberau** [comment]
as I said, I am not an export on JavaScript, but I think "to ensure that you are not moving a task to a different board and therefore to a different project" exactly solves the problem I have. Most cases it seems I have the issue (without bigboard installed) when I temporarily move a task "outside" the area of the project in the browser as can be seen on the video I attached to the kanboard issue.
