### ISSUE TITLE
Title of tasks are not clickable with new Kanboard

### ISSUE THREAD

**Issue by TheCloud** [stinnux/kanboard-bigboard#2]
When I click on a title, it does not open the task when tasks are collapsed.
can the "view" of the tasks be inherit the same layout as kanboard ?

**Comment by TheCloud** [comment]
I edited the file task_private and replaced line:
`<?= $this->url->link($this->text->e($task['title']), 'TaskViewController', 'show', array('task_id' => $task['id'], 'project_id' => $task['project_id']), false, null, $this->text->e($task['title'])) ?>*`
With a more simple:
`<span title="<?=$this->text->e($task['title']);?>"><?=$this->text->e($task['title']);?></span>`

And works

**Comment by stinnux** [comment]
I don't see any issues opening the task view with the current kanboard version in the master branch.

I also do not see how your fix should be working, since it does not even contain a link. 

Can you send me a PR?

**Comment by TheCloud** [comment]
Hello @stinnux do you have the tasks assigned to someone ?
The behaviour I see is that only the assignee initials are clickable, when view is collapsed.

The fix works because the SPAN is already linked via javascript event so the link, again in collapsed view, conflicts with the existing event.

To reproduce:
a) collapse view
b) assign task to user
c) click task title => nothing happens
d) click on assignee's initials => taks opens

Let me know if you are able to reproduce.
Julien

**Comment by stinnux** [comment]
Please check new Release 1.0.1
