### ISSUE TITLE
Update Plugin Repository to 1.0.6

### ISSUE THREAD

**Issue by TimoStahl** [stinnux/kanboard-bigboard#25]
Hi @stinnux,

could you please update your plugin in https://github.com/kanboard/website/blob/master/plugins.json to 1.0.6 to get the lastest version via kanboard inline installer.

It might be possible that you have to change your latest release from .tar.gz to zip as you did earlier.

I saw that you repository isn't maintained anymore (#20) if you grant me some permissions, I will check the latest pull requests and create a new version.

Thanks

**Comment by johnwoltman** [comment]
@stinnux, if you could make time to review @BlueTeck's request, that would be wonderful.  It'd be nice to have this useful plugin updated.

**Comment by TimoStahl** [comment]
@johnwoltman I've created my own fork and changed some things https://github.com/BlueTeck/kanboard_plugin_bigboard maybe this could help you

**Comment by johnwoltman** [comment]
> 
> 
> @johnwoltman I've created my own fork and changed some things https://github.com/BlueTeck/kanboard_plugin_bigboard maybe this could help you

Thanks BlueTeck! Do you have any plans to update Kanboard's plugins.json to point to your repo?

**Comment by TimoStahl** [comment]
I will in the next days

**Comment by TimoStahl** [comment]
Pull Request https://github.com/kanboard/website/pull/227
